// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const add = `-- name: Add :exec
INSERT INTO incidents (
        id, title, severity, service_name, started_at, resolved_at
        ) 
    VALUES (
        $1, $2, $3, $4, $5, $6
        )
`

type AddParams struct {
	ID          string
	Title       string
	Severity    string
	ServiceName string
	StartedAt   pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add,
		arg.ID,
		arg.Title,
		arg.Severity,
		arg.ServiceName,
		arg.StartedAt,
		arg.ResolvedAt,
	)
	return err
}

const deleteAll = `-- name: DeleteAll :exec
DELETE FROM incidents
`

func (q *Queries) DeleteAll(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAll)
	return err
}

const deleteByID = `-- name: DeleteByID :exec
DELETE FROM incidents
WHERE id = $1
`

func (q *Queries) DeleteByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteByID, id)
	return err
}

const edit = `-- name: Edit :exec
UPDATE incidents
    SET id = $1,
    title = $2,
    severity = $3,
    service_name = $4,
    started_at = $5,
    resolved_at = $6
WHERE id = $7
RETURNING id, title, severity, service_name, started_at, resolved_at, is_resolved
`

type EditParams struct {
	ID          string
	Title       string
	Severity    string
	ServiceName string
	StartedAt   pgtype.Timestamptz
	ResolvedAt  pgtype.Timestamptz
	ID_2        string
}

func (q *Queries) Edit(ctx context.Context, arg EditParams) error {
	_, err := q.db.Exec(ctx, edit,
		arg.ID,
		arg.Title,
		arg.Severity,
		arg.ServiceName,
		arg.StartedAt,
		arg.ResolvedAt,
		arg.ID_2,
	)
	return err
}

const getAll = `-- name: GetAll :many
SELECT id, title, severity, service_name, started_at, resolved_at, is_resolved FROM incidents
`

func (q *Queries) GetAll(ctx context.Context) ([]Incident, error) {
	rows, err := q.db.Query(ctx, getAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Incident
	for rows.Next() {
		var i Incident
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Severity,
			&i.ServiceName,
			&i.StartedAt,
			&i.ResolvedAt,
			&i.IsResolved,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByID = `-- name: GetByID :one
SELECT id, title, severity, service_name, started_at, resolved_at, is_resolved FROM incidents
WHERE id = $1
`

func (q *Queries) GetByID(ctx context.Context, id string) (Incident, error) {
	row := q.db.QueryRow(ctx, getByID, id)
	var i Incident
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Severity,
		&i.ServiceName,
		&i.StartedAt,
		&i.ResolvedAt,
		&i.IsResolved,
	)
	return i, err
}
